### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by maofengggg** [rdevon/cortex#213]
Hi Dr.RDevon
When I run the code cortex GAN --d.source CIFAR10 --d.copy_to_local after I setup the cortex, it still throw a error as:
[INFO:cortex]: Setting logging to INFO                                        
Traceback (most recent call last):
  File "/home/mtang4/anaconda3/envs/IARPA2/bin/cortex", line 8, in <module>
    sys.exit(run())
  File "/home/mtang4/anaconda3/envs/IARPA2/lib/python3.6/site-packages/cortex/main.py", line 32, in run
    config.set_config()
  File "/home/mtang4/anaconda3/envs/IARPA2/lib/python3.6/site-packages/cortex/_lib/config.py", line 79, in set_config
    d = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
Can you help me?

**Comment by Forainest789** [comment]
Find solution here, it may have wrong with pyyaml
try 
```shell
pip install pyyaml==5.4.1
```
